#! /usr/bin/env python3
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#    Dec 22, 2022 09:50:32 PM IST  platform: Windows NT

import sys
import tkinter as tk
import tkinter.ttk as ttk
from tkinter.constants import *

import unknown
import driver

pen = driver.mouse.Listener(on_click=driver.on_click, on_move=driver.on_move)

_debug = True # False to eliminate debug printing from callback functions.

def main(*args):
    '''Main entry point for the application.'''
    global root
    root = tk.Tk()
    root.protocol( 'WM_DELETE_WINDOW' , root.destroy)
    # Creates a toplevel widget.
    global top1, w1
    top1 = root
    w1 = unknown.Toplevel1(top1)
    pen.start()
    root.mainloop()
    pen.stop()

if __name__ == '__main__':
    unknown.start_up()




