#############################################################################
# Generated by PAGE version 7.6
#  in conjunction with Tcl version 8.6
#  Dec 22, 2022 02:05:27 PM IST  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    ::vTcl::MessageBox -title Error -message  "You must open project files from within PAGE."
    exit}


set image_list { 
}
vTcl:create_project_images $image_list   ;# In image.tcl

if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
########################################### 
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) gray40
set vTcl(analog_color_p) #c3c3c3
set vTcl(analog_color_m) beige
set vTcl(tabfg1) black
set vTcl(tabfg2) black
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
########################################### 
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top1 {base} {
    global vTcl
    if {$base == ""} {
        set base .top1
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    set target $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 960x517+334+117
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1540 825
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    set toptitle "Toplevel 0"
    wm title $top $toptitle
    namespace eval ::widgets::${top}::ClassOption {}
    set ::widgets::${top}::ClassOption(-toptitle) $toptitle
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    menu "$top.m49" \
        -activebackground $vTcl(actual_gui_menu_analog) \
        -activeforeground #000000 -background $vTcl(actual_gui_menu_bg) \
        -font "TkMenuFont" -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    
set site_3_0 $top.m49
    $top.m49 add cascade \
        -menu "$top.m49.men50" -compound left -label "File" 
    menu "$site_3_0.men50" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    
set site_4_0 $site_3_0.men50
    $site_3_0.men50 add cascade \
        -menu "$site_3_0.men50.men51" -command "{}" -compound left \
        -label "New" 
    menu "$site_4_0.men51" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    $site_4_0.men51 add command \
        -command "#" -compound left -label "Notebook" 
    $site_4_0.men51 add command \
        -command "#" -compound left -label "Page" 
    $site_3_0.men50 add command \
        -command "#" -compound left -label "Open (Ctrl + O)" 
    $site_3_0.men50 add command \
        -command "#" -compound left -label "Save(Ctrl +S)" 
    $site_3_0.men50 add command \
        -command "#" -compound left -label "Save As.." 
    $site_3_0.men50 add command \
        -command "#" -compound left -label "Close.." 
    
set site_3_0 $top.m49
    $top.m49 add cascade \
        -menu "$top.m49.men52" -compound left -label "Edit" 
    menu "$site_3_0.men52" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men52 add command \
        -command "#" -compound left -label "Undo (Ctrl +Z)" 
    $site_3_0.men52 add command \
        -command "#" -compound left -label "Redo (Ctrl + Y)" 
    $site_3_0.men52 add command \
        -command "#" -compound left -label "Paste (Ctrl +V)" 
    
set site_3_0 $top.m49
    $top.m49 add cascade \
        -menu "$top.m49.men47" -compound left -label "Options" 
    menu "$site_3_0.men47" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    
set site_4_0 $site_3_0.men47
    $site_3_0.men47 add cascade \
        -menu "$site_3_0.men47.men48" -command "{}" -compound left \
        -label "Theme" 
    menu "$site_4_0.men48" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    $site_4_0.men48 add radiobutton \
        -value "Light" -variable "menuSelectedButton" -command "#" \
        -compound left -label "Light" 
    $site_4_0.men48 add radiobutton \
        -value "Dark" -variable "menuSelectedButton" -command "#" \
        -compound left -label "Dark" 
    $site_3_0.men47 add command \
        -command "#" -compound left -label "Sync" 
    
set site_4_0 $site_3_0.men47
    $site_3_0.men47 add cascade \
        -menu "$site_3_0.men47.men50" -command "{}" -compound left \
        -label "Connect" 
    menu "$site_4_0.men50" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    $site_4_0.men50 add command \
        -command "#" -compound left -label "GDrive" 
    $site_4_0.men50 add command \
        -command "#" -compound left -label "OneDrive" 
    $site_4_0.men50 add command \
        -command "#" -compound left -label "Mega" 
    
set site_3_0 $top.m49
    $top.m49 add cascade \
        -menu "$top.m49.men53" -compound left -label "Help" 
    menu "$site_3_0.men53" \
        -activebackground beige -activeforeground black \
        -background $vTcl(actual_gui_menu_bg) -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_menu_fg) -tearoff 0 
### SPOT dump_widget_opt A
    $site_3_0.men53 add command \
        -command "#" -compound left -label "About PyNote" 
    $site_3_0.men53 add command \
        -command "#" -compound left -label "Open Help" 
    ttk::style configure TNotebook -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -background $vTcl(actual_gui_bg)
    ttk::style configure TNotebook.Tab -foreground $vTcl(actual_gui_fg)
    ttk::style configure TNotebook.Tab -font "$vTcl(actual_gui_font_dft_desc)"
    ttk::style map TNotebook.Tab -background [list selected $vTcl(actual_gui_bg) active $vTcl(tabbg1) !active $vTcl(tabbg2)]
    ttk::style map TNotebook.Tab -foreground [list selected $vTcl(actual_gui_fg) active $vTcl(tabfg1) !active $vTcl(tabfg2)]
    ttk::notebook "$top.tNo52" \
        -width 986 -height 495 -takefocus {} 
    vTcl:DefineAlias "$top.tNo52" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    frame "$top.tNo52.t0" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo52.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.tNo52 add $top.tNo52.t0 \
        -padding 0 -sticky nsew -state normal -text "Page 1" -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo52.t0
    frame "$site_4_0.fra47" \
        -borderwidth 2 -relief groove -background $vTcl(actual_gui_bg) \
        -height 475 -width 960 
    vTcl:DefineAlias "$site_4_0.fra47" "Frame1" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    vTcl:copy_lock $site_4_0.fra47
    place $site_4_0.fra47 \
        -in $site_4_0 -x 0 -y 0 -width 0 -relwidth 0.978 -height 0 \
        -relheight 1.011 -anchor nw -bordermode ignore 
    frame "$top.tNo52.t1" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo52.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.tNo52 add $top.tNo52.t1 \
        -padding 0 -sticky nsew -state normal -text "Page 2" -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo52.t1
    frame "$top.tNo52.t2" \
        -background $vTcl(actual_gui_bg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black 
    vTcl:DefineAlias "$top.tNo52.t2" "TNotebook1_t3" vTcl:WidgetProc "Toplevel1" 1
### SPOT dump_widget_opt A
    $top.tNo52 add $top.tNo52.t2 \
        -padding 0 -sticky nsew -state normal -text "New Page" -image {} \
        -compound left -underline -1 
    set site_4_2  $top.tNo52.t2
    vTcl:copy_lock $top.tNo52
    vTcl::widgets::core::popup::createCmd "$top.pop48" \
        -activebackground $vTcl(analog_color_m) -activeborderwidth 1 \
        -activeforeground black -background $vTcl(actual_gui_bg) \
        -borderwidth 1 -disabledforeground #a3a3a3 -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_fg) -tearoff 1 
    global vTcl
    set val vTcl($top.pop48,-proc)
    set vTcl($top.pop48,-proc) popup1
    namespace eval ::widgets::$top.pop48 {}
    set ::widgets::$top.pop48::ClassOption(-proc) popup1
    set ::widgets::$top.pop48::options(-proc) popup1
    set ::widgets::$top.pop48::save(-proc) 1
    vTcl:DefineAlias "$top.pop48" "Popupmenu1" vTcl:WidgetProc "" 1
### SPOT dump_widget_opt A
    vTcl::widgets::core::popup::createCmd "$top.pop49" \
        -activebackground $vTcl(analog_color_m) -activeborderwidth 1 \
        -activeforeground black -background $vTcl(actual_gui_bg) \
        -borderwidth 1 -disabledforeground #a3a3a3 -font "TkMenuFont" \
        -foreground $vTcl(actual_gui_fg) -tearoff 1 
    global vTcl
    set val vTcl($top.pop49,-proc)
    set vTcl($top.pop49,-proc) popup2
    namespace eval ::widgets::$top.pop49 {}
    set ::widgets::$top.pop49::ClassOption(-proc) popup2
    set ::widgets::$top.pop49::options(-proc) popup2
    set ::widgets::$top.pop49::save(-proc) 1
    vTcl:DefineAlias "$top.pop49" "Popupmenu2" vTcl:WidgetProc "" 1
### SPOT dump_widget_opt A
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.tNo52 \
        -in $top -x 0 -y 0 -width 0 -relwidth 1.027 -height 0 \
        -relheight 0.959 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

proc 36 {args} {return 1}


Window show .
set btop1 ""
if {$vTcl(borrow)} {
    set btop1 .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop1 $vTcl(tops)] != -1} {
        set btop1 .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop1
Window show .top1 $btop1
if {$vTcl(borrow)} {
    $btop1 configure -background plum
}

